### PR TITLE
update transform-vue-jsx to 4.0.1

### PR DESCRIPTION
**Pull request by fjc0k**
for Babel 7

### CODE REVIEW

**Comment by egoist** [comment]
Can you update the lockfile as well?

**Comment by fjc0k** [comment]
@egoist o la...

**Comment by jarvelov** [comment]
Is there a release coming with this? Currently the version on npm uses transform-vue-jsx@3.5.0.

**Comment by wangxingkai** [comment]
Can we publish a new release to have this `babel-plugin-transform-vue-jsx` version upgraded? @egoist

**Pull request merged**
